# Generated by Django 4.1.6 on 2023-04-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('text', models.TextField(max_length=800)),
                ('number', models.IntegerField()),
                ('positive_num', models.PositiveIntegerField()),
            ],
        ),
    ]
