# Generated by Django 4.1.6 on 2023-04-28 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('published_date', models.DateField()),
                ('image', models.ImageField(upload_to='uploads')),
                ('book_pdf', models.FileField(upload_to='uploads')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.author')),
            ],
        ),
    ]
